// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBNh_aKHW-E0Jltgi7HdQVqe0710CgRjpg",
    authDomain: "yoruphonics-v2.firebaseapp.com",
    projectId: "yoruphonics-v2",
    storageBucket: "yoruphonics-v2.firebasestorage.app",
    messagingSenderId: "676941103224",
    appId: "1:676941103224:web:f9831d9a643ddc98962d8d",
    measurementId: "G-X1SCE5PNBR",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD9G2MT16my_SGkCf3HOg7IHMyY0bWCdw',
    appId: '1:676941103224:android:300c4f82c37705c0962d8d',
    messagingSenderId: '676941103224',
    projectId: 'yoruphonics-v2',
    storageBucket: 'yoruphonics-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQUrSfZnqOaYigeg5_gH5xLFSA0_4Dse4',
    appId: '1:676941103224:ios:bb4565195c46a4be962d8d',
    messagingSenderId: '676941103224',
    projectId: 'yoruphonics-v2',
    storageBucket: 'yoruphonics-v2.firebasestorage.app',
    iosBundleId: 'com.example.yoruphonicsV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQUrSfZnqOaYigeg5_gH5xLFSA0_4Dse4',
    appId: '1:676941103224:ios:bb4565195c46a4be962d8d',
    messagingSenderId: '676941103224',
    projectId: 'yoruphonics-v2',
    storageBucket: 'yoruphonics-v2.firebasestorage.app',
    iosBundleId: 'com.example.yoruphonicsV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNh_aKHW-E0Jltgi7HdQVqe0710CgRjpg',
    appId: '1:676941103224:web:0ac666b1ab0a9cfa962d8d',
    messagingSenderId: '676941103224',
    projectId: 'yoruphonics-v2',
    authDomain: 'yoruphonics-v2.firebaseapp.com',
    storageBucket: 'yoruphonics-v2.firebasestorage.app',
    measurementId: 'G-XESNVVNLTQ',
  );
}
